export const projectsList = [
  {
    id: 1,
    title: 'Apex Legal Shield',
    desc: 'A premium, high-trust website layout for a global defense law practice with automated scheduling integrations.',
    image: '/images/ChatGPT Image Jul 4, 2026, 07_29_50 PM.png',
    tags: ['Next.js', 'CSS Modules', 'Legal Tech'],
  },
  {
    id: 2,
    title: 'Nova Analytics Panel',
    desc: 'An AI-powered landing page and SaaS registration pipeline designed to drive monthly recurring subscription revenue.',
    image: '/images/ChatGPT Image Jul 4, 2026, 07_31_36 PM.png',
    tags: ['SaaS Portal', 'AI Systems', 'React Hooks'],
  },
  {
    id: 3,
    title: 'VibeCart E-Store',
    desc: 'A luxury, highly optimized clothing brand store featuring cart controls and custom Stripe checkout transitions.',
    image: '/images/ChatGPT Image Jul 4, 2026, 07_33_12 PM.png',
    tags: ['E-Commerce', 'Payment APIs', 'Animations'],
  },
  {
    id: 4,
    title: 'FitAI Personal Coach',
    desc: 'Interactive marketing landing page for a healthtech startup offering custom AI-generated workout strategies.',
    image: '/images/ChatGPT Image Jul 4, 2026, 07_37_05 PM.png',
    tags: ['Landing Page', 'Mobile First', 'Healthtech'],
  },
  {
    id: 5,
    title: 'AeroSaaS Automation',
    desc: 'Clean, modern homepage showcasing automated workflows and cross-platform syncing dashboards.',
    image: '/images/ChatGPT Image Jul 4, 2026, 07_38_45 PM.png',
    tags: ['Software', 'SEO Schema', 'Framer'],
  },
  {
    id: 6,
    title: 'Nexus Cloud CRM Portal',
    desc: 'Customer relationship landing page built specifically to accelerate enterprise lead generation.',
    image: '/images/ChatGPT Image Jul 4, 2026, 07_42_16 PM.png',
    tags: ['Enterprise', 'Core Web Vitals', 'B2B'],
  },
  {
    id: 7,
    title: 'Acme Corporate Hub',
    desc: 'Corporate business website built with fluid layouts and high contrast accessibility standards.',
    image: '/images/ChatGPT Image Jul 4, 2026, 07_45_03 PM.png',
    tags: ['Business Site', 'Accessbility', 'Next.js'],
  },
  {
    id: 8,
    title: 'Zeta Crypto Exchange',
    desc: 'High-security financial landing page displaying active market tags and digital asset options.',
    image: '/images/ChatGPT Image Jul 4, 2026, 07_47_24 PM.png',
    tags: ['Fintech', 'Dark Mode', 'Security'],
  },
  {
    id: 9,
    title: 'Lumina Creative Agency',
    desc: 'Frosted-glass themed layout presenting portfolio work and client testimonials for a design agency.',
    image: '/images/ChatGPT Image Jul 4, 2026, 07_48_32 PM.png',
    tags: ['Creative Agency', 'Glassmorphic', 'UX'],
  },
  {
    id: 10,
    title: 'Pulse Medical Clinic',
    desc: 'Highly secure, HIPAA-compliant patient communication portal and local clinic website.',
    image: '/images/ChatGPT Image Jul 4, 2026, 07_52_08 PM.png',
    tags: ['Healthcare', 'Secured API', 'Trust Builder'],
  },
  {
    id: 11,
    title: 'Prime Estate Catalog',
    desc: 'Real estate catalog site featuring advanced search filters, local maps, and contact captures.',
    image: '/images/ChatGPT Image Jul 4, 2026, 07_53_39 PM.png',
    tags: ['Real Estate', 'Listing Filter', 'Map SDK'],
  },
  {
    id: 12,
    title: 'Horizon School Portal',
    desc: 'E-learning homepage showcasing interactive courses, virtual classroom lists, and schedules.',
    image: '/images/ChatGPT Image Jul 4, 2026, 07_55_17 PM.png',
    tags: ['Education', 'CMS Sync', 'Lighthouse 100'],
  },
  {
    id: 13,
    title: 'ByteCode Tech Blog',
    desc: 'Fast, search-engine-optimized news blog featuring standard categories, breadcrumbs, and tags.',
    image: '/images/ChatGPT Image Jul 4, 2026, 07_56_50 PM.png',
    tags: ['Tech Blog', 'Schema Markup', 'SSG'],
  },
  {
    id: 14,
    title: 'Vanguard Ventures Group',
    desc: 'Vibrant cobalt blue business portal targeting global investment advisory trust leads.',
    image: '/images/ChatGPT Image Jul 4, 2026, 07_58_36 PM.png',
    tags: ['Investments', 'B2B Leads', 'Blue Gradient'],
  },
  {
    id: 15,
    title: 'Sustain Energy Solutions',
    desc: 'Product portfolio site explaining green solar installations and capturing quote requests.',
    image: '/images/ChatGPT Image Jul 4, 2026, 08_01_36 PM.png',
    tags: ['Cleantech', 'Custom SVG', 'SSR'],
  },
  {
    id: 16,
    title: 'Aura Spa & Wellness',
    desc: 'Calming, aesthetic wellness center layout featuring interactive service menus and reviews.',
    image: '/images/ChatGPT Image Jul 4, 2026, 08_03_34 PM.png',
    tags: ['Local Business', 'Spa Wellness', 'Booking Form'],
  },
  {
    id: 17,
    title: 'Apex Law Office Website',
    desc: 'Corporate defense platform designed with clean typography and custom organizational JSON-LD.',
    image: '/images/ChatGPT Image Jul 4, 2026, 08_05_13 PM.png',
    tags: ['Legal Firm', 'Trust Badge', 'B2B'],
  },
  {
    id: 18,
    title: 'VibeCart Luxury Boutique',
    desc: 'Modern online clothing boutique with responsive card grids and smooth hover image zooms.',
    image: '/images/ChatGPT Image Jul 4, 2026, 08_08_07 PM.png',
    tags: ['E-Store', 'Stripe checkout', 'Mobile Optimization'],
  },
  {
    id: 19,
    title: 'FitAI Workout Dashboard',
    desc: 'User platform showing tracking calendars, calories, and personalized AI workout lists.',
    image: '/images/ChatGPT Image Jul 4, 2026, 08_10_20 PM.png',
    tags: ['React App', 'AI Personalizer', 'Tailwind'],
  },
  {
    id: 20,
    title: 'Acme SaaS CRM Platform',
    desc: 'Enterprise workflow dashboard featuring visual graph tables and dynamic list overlays.',
    image: '/images/ChatGPT Image Jul 4, 2026, 08_11_36 PM.png',
    tags: ['SaaS Platform', 'B2B SaaS', 'Analytics Grid'],
  },
  {
    id: 21,
    title: 'Acme SaaS Admin Console',
    desc: 'Customer onboarding registration flow built with secure Next.js server actions.',
    image: '/images/ChatGPT Image Jul 4, 2026, 08_12_50 PM.png',
    tags: ['SaaS Console', 'Forms Validation', 'Next.js'],
  },
  {
    id: 22,
    title: 'Lumina Design Showcase',
    desc: 'Visual gallery platform presenting multi-category imagery and responsive modal zooms.',
    image: '/images/ChatGPT Image Jul 4, 2026, 08_14_30 PM.png',
    tags: ['Design Show', 'Glassmorphism', 'Grid Layout'],
  },
  {
    id: 23,
    title: 'Acme Business Portal v2',
    desc: 'Modernized landing page featuring rich cobalt gradients and custom 3D illustration mockups.',
    image: '/images/ChatGPT Image Jul 4, 2026, 08_17_15 PM.png',
    tags: ['Corporate Hub', 'Cobalt Theme', 'UX Upgrade'],
  },
  {
    id: 24,
    title: 'Acme Corporate Hub v2',
    desc: 'Updated corporate presentation website featuring key metrics, delivered project numbers, and client maps.',
    image: '/images/ChatGPT Image Jul 4, 2026, 08_18_22 PM.png',
    tags: ['Business Site', 'B2B Client Map', 'Lighthouse 100'],
  },
  {
    id: 25,
    title: 'Zeta Financial Exchange v2',
    desc: 'High-performance crypto analytics dashboard showing active tickers and historical line charts.',
    image: '/images/ChatGPT Image Jul 4, 2026, 08_19_39 PM.png',
    tags: ['Fintech Exchange', 'Live Tickers', 'Chart.js'],
  },
  {
    id: 26,
    title: 'Prime Estate Catalog v2',
    desc: 'Upgraded real estate site showing high definition properties, client inquiries, and interactive contact forms.',
    image: '/images/ChatGPT Image Jul 4, 2026, 08_21_00 PM.png',
    tags: ['Real Estate', 'HD Property Slider', 'Lead Gen'],
  },
  {
    id: 27,
    title: 'Lumina Creative Agency v2',
    desc: 'Modernized design boutique with animated background particles and mouse-follow glow effects.',
    image: '/images/ChatGPT Image Jul 4, 2026, 08_22_33 PM.png',
    tags: ['Creative Agency', 'Particle Animation', 'UX'],
  },
  {
    id: 28,
    title: 'Acme SaaS Admin Console v2',
    desc: 'Optimized registration tunnel and multi-factor authentication setup for SaaS products.',
    image: '/images/ChatGPT Image Jul 4, 2026, 08_24_42 PM.png',
    tags: ['SaaS Console', 'Secure Auth', 'Fast Load'],
  },
  {
    id: 29,
    title: 'Acme Corporate Hub v3',
    desc: 'Refined enterprise homepage styled with premium glassmorphic cards and glowing top borders.',
    image: '/images/ChatGPT Image Jul 4, 2026, 08_26_00 PM.png',
    tags: ['Enterprise Hub', 'Glow Border', 'Premium Card'],
  },
  {
    id: 30,
    title: 'Aura Spa & Wellness v2',
    desc: 'Aesthetic therapy landing page featuring online appointment bookings and pricing estimators.',
    image: '/images/ChatGPT Image Jul 4, 2026, 08_27_29 PM.png',
    tags: ['Wellness Center', 'Booking App', 'Aesthetic UI'],
  },
  {
    id: 31,
    title: 'Lumina Design Studio v3',
    desc: 'Advanced agency showcase displaying multi-resolution screen captures and custom layouts.',
    image: '/images/ChatGPT Image Jul 4, 2026, 08_45_35 PM.png',
    tags: ['Agency Show', 'Glassmorphism', 'Responsive Grid'],
  },
  {
    id: 32,
    title: 'Pulse Medical Clinic v2',
    desc: 'Secure telehealth scheduling application showing dynamic patient queues and doctor ratings.',
    image: '/images/ChatGPT Image Jul 4, 2026, 08_47_40 PM.png',
    tags: ['Telehealth', 'Secure Scheduling', 'HIPAA compliant'],
  },
  {
    id: 33,
    title: 'Acme Business Portal v3',
    desc: 'Enterprise landing page optimization project with custom sub-second loading speed modifications.',
    image: '/images/ChatGPT Image Jul 4, 2026, 09_06_03 PM.png',
    tags: ['Corporate Hub', 'Speed Optimization', 'Vitals Rank'],
  },
  {
    id: 34,
    title: 'Zeta Financial Exchange v3',
    desc: 'High-frequency trading interface and secure account registration dashboard.',
    image: '/images/ChatGPT Image Jul 4, 2026, 09_16_23 PM.png',
    tags: ['Crypto Exchange', 'MFA Auth', 'Security Vault'],
  },
  {
    id: 35,
    title: 'Sustain Energy Solutions v2',
    desc: 'Green energy analytics dashboard presenting solar savings calculations over custom charts.',
    image: '/images/ChatGPT Image Jun 21, 2026, 09_28_42 AM.png',
    tags: ['Cleantech SaaS', 'Savings Calculator', 'Chart Grid'],
  },
  {
    id: 36,
    title: 'Acme Corporate Hub v4',
    desc: 'Premium multi-language homepage presenting global services and local landing layouts.',
    image: '/images/ChatGPT Image May 29, 2026, 01_29_10 AM.png',
    tags: ['Enterprise Hub', 'Multi-Language', 'Worldwide CDN'],
  },
];
